### ISSUE TITLE
cannot reach Sormas on the web

### ISSUE THREAD

**Issue by RafaelKluender** [hzi-braunschweig/SORMAS-Docker#7]
I installed the sormas-docker as described. When I run docker-compose up, everything starts, but I cannot access the sormas website (hostname: https://sormas-docker-test.com/)

The error on server side is: 
 "GET / HTTP/1.1" 302 215

**Comment by fhauptmann** [comment]
Did you set the entry in the host file, like described in the README?
Please provide more information, screenshots or web server logs.

**Comment by RafaelKluender** [comment]
Looks like this is a problem with the Domain Name. 
The website is accessible under: 
https://IP/sormas-ui/login

**Comment by sgatibaru** [comment]
Please help,

I didn't make changes to the hosts as I couldnt run the install when I did. 
I changed the server-url to http://localhost

I get a message of 

> "It works!"

@fhauptmann would you have a solution? 

The apache output is 

"GET / HTTP/1.1" 200 45

**Comment by TomHutter** [comment]
Have you tried http://localhost/sormas-ui/login ? Maybe something with the redirect isn't working correct, when using only http://localhost.

**Comment by sgatibaru** [comment]
@TomHutter I'm trying to use a live server. I created a clean install on an Ubuntu 16.04 server.. I just did a url redirect to a sub-domain on my web-server with both the, and still I can't get it to work. I've gone through all the steps given & I still can't get it to work. My server address is 161.35.8.69..

I finally just made a redirect through my cpanel through my subdomain, https://s.naivacargo.co.ke/sormas-ui/ which gives me a 404 error.. (I've used the letsencrypt certificates from the server's subdomain..)

I've gone through the configuration steps severally & still can't seem to get it working.

**Comment by TomHutter** [comment]
There is a variable in .env:
`SORMAS_SERVER_URL=`
Have you set it to: `SORMAS_SERVER_URL=s.naivacargo.co.ke` ?

**Comment by sgatibaru** [comment]
> There is a variable in .env:
> `SORMAS_SERVER_URL=`
> Have you set it to: `SORMAS_SERVER_URL=s.naivacargo.co.ke` ?

Yes I have.. I'm completely can't get it to run even using the repo from [sampsonorson](https://github.com/sampsonorson/SORMAS-Open) I don't like failing but i'm not sure this will ever run.. Maybe there's something thats been left out .. I'll make one last attempt on both the Docker & server then leave this project..

**Comment by TomHutter** [comment]
What happens, if you try to call the URL via curl on the host running the docker containers?

`curl -k -L --resolve 's.naivacargo.co.ke:443:127.0.0.1' https://s.naivacargo.co.ke`

This should redirect you to the login page, showing you something like:

```
<!doctype html>
<html>
...
 <body scroll="auto" class="v-generated-body">
  <div id="sormasuilogin-1969194708" class="v-app sormas loginui">
   <div class="v-app-loading"></div>
   <noscript>
    You have to enable javascript in your browser to use an application built with Vaadin.
   </noscript>
  </div>
 </body>
</html>
```

**Comment by sgatibaru** [comment]
I tried,
>  `curl -k -L --resolve 's.naivacargo.co.ke:443:127.0.0.1' https://s.naivacargo.co.ke`

and didn't get through. With a change of the hosts file, I used my IP & only then did I get the result I'd intended. 

I was at this the whole of yesterday. I destroyed and created a whole new droplet with an IP of 167.71.160.237.

Kindly, if you please may, I would be grateful if have a look at my configuration..
```

> ssh sky@167.71.160.237
> password: inspired

```

![ .env file ](https://user-images.githubusercontent.com/25096223/78334764-030d4680-7595-11ea-8c3b-df17ba3cfb7e.png)

![ /etc/hosts file ](https://user-images.githubusercontent.com/25096223/78334803-14eee980-7595-11ea-9ed5-63bca3c0743a.png)

![the page](https://user-images.githubusercontent.com/25096223/78334838-246e3280-7595-11ea-9a47-a05f27d567cf.png)

one of the errors apache gives is:
`apache2_1   | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message`

**Comment by licks0re** [comment]
@sgatibaru 

Your site is up and running @ https://s.naivacargo.co.ke/

The certificates are self signed so your browser will alert you, it won't if you buy a cert for the domain "naivacargo.co.ke" I guess.

It's really a bad idea to post login / password on internet, I hope nobody will break your stuff...

What was missing? 

Define proper domain in the .env

`SORMAS_POSTGRES_PASSWORD=password

SORMAS_POSTGRES_USER=sormas_user
SORMAS_VERSION=1.37.1
SORMAS_SERVER_URL=s.naivacargo.co.ke

DB_HOST=postgres
DOMAIN_NAME=sormas
DB_NAME=sormas
DB_NAME_AUDIT=sormas_audit
LOCALE=de
EPIDPREFIX=DEU
MAIL_HOST=localhost
SEPARATOR=\;
EMAIL_SENDER_ADDRESS=noreply@sormas-docker-test.com
EMAIL_SENDER_NAME=SORMAS
LONGITUDE=52.2109803
LATITUDE=10.5314925
MAIL_FROM="root@localhost"
SORMAS_PATH=/srv/dockerdata/sormas
JVM_MAX=4096m
TZ=Europe/Berlin
`

Create key and certificate in /root/SORMAS-Docker/apache2/certs

```
openssl genrsa 2048 > s.naivacargo.co.ke.key
chmod +400 /root/SORMAS-Docker/apache2/certs/s.naivacargo.co.ke.key
openssl req -new -x509 -nodes -sha256 -days 365 -key s.naivacargo.co.ke.key -out s.naivacargo.co.ke.crt
```

Then, 

`docker-compose up -d `

That's all. Have a good day, don't forget to change login / password etc ( I would suggest a complete reinstall of your server, you never what some ppl could have done)... :)

**Comment by licks0re** [comment]
Funny thing, on your setup, like on mine, the 

```
LONGITUDE=52.2109803
LATITUDE=10.5314925
```

of the .env files are not working...

**Comment by TomHutter** [comment]
@licks0re : Thanks for the great support :-)

**Comment by TomHutter** [comment]
> Funny thing, on your setup, like on mine, the
> 
> ```
> LONGITUDE=52.2109803
> LATITUDE=10.5314925
> ```
> 
> of the .env files are not working...

Well, there was an issue with swapped lat / lon. But this should be fixed in v1.37.1.

Nevertheless the lat / lon from the .env file are used in the [docker-compose.yml](https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/docker-compose.yml) line 25,26 for the sormas container. And then used to set the sormas.properties in the  in the container during startup in the [start-server.sh](https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/sormas/start-server.sh) script line 81,82

**Comment by licks0re** [comment]
> @licks0re : Thanks for the great support :-)

That's normal, no problem!


`Well, there was an issue with swapped lat / lon. But this should be fixed in v1.37.1.`

Ah, I didn't know and it didn't tilted my mind, thanks for pointing that out, I'll update my .env.
I don't think it's fixed yet in 1.37.1, but you gave the solution, thanks !  💯 

Have a good day,
Guillaume
